### ISSUE TITLE
Your platform/architecture combination NaN is not yet supported. Windows 10

### ISSUE THREAD

**Issue by djleonskennedy** [bazelbuild/bazel-watcher#116] opened 2018-01-14 12:02 UTC
Hello

all prerequisites installed

cannot start devserver, Windows 10

```
$ ./node_modules/.bin/ibazel run src:devserver
FATAL: Your platform/architecture combination NaN is not yet supported.
    Follow install instructions at https://github.com/bazelbuild/bazel-watcher/blob/master/README.md to compile for your system.

```
package.json

```
{
  "scripts": {
    "build": "bazel run @yarn//:yarn",
    "prebuildifier": "bazel build @com_github_bazelbuild_buildtools//buildifier",
    "buildifier": "find . -type f \\( -name BUILD -or -name BUILD.bazel \\) ! -path \"./node_modules/*\" | xargs $(bazel info bazel-bin)/external/com_github_bazelbuild_buildtools/buildifier/buildifier"
  },
  "dependencies": {
    "@bazel/ibazel": "^0.2.0",
    "@bazel/typescript": "^0.6.0",
    "rxjs": "^5.5.6",
    "typescript": "^2.6.2"
  }
}
```

Thank you

**Comment by webdevelopland** [comment] 2018-02-06 05:47
+1

**Comment by achew22** [comment] 2018-02-06 05:58
This is a duplicate of #105. Closing in favor of that.

**Closed by achew22** 2018-02-06 05:58 UTC
