### ISSUE TITLE
ibazel not exiting on Ctrl-C on Mac OS after shutting down child process

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel-watcher#50] opened 2017-10-16 22:08 UTC
Not sure what's going on elsewhere, but when I run a server with `ibazel`, and hit ctrl-c, I get

     Subprocess killed from getting SIGINT

but the prompt freezes and the ibazel process does not exit.

This is happening with current HEAD, e8cbba37f5aa56f36e8561ec64128008c1f2cbe1

**Comment by jmhodges** [comment] 2017-10-16 22:09
A second ctrl-c does make it go away. Seems like there's a bug?

**Comment by achew22** [comment] 2017-10-17 02:10
Yep, that's how I implemented it. The first ctrl-c terminates the subtask then the second one kills ibazel. If the subtask doesn't shut down after 3 attempts to kill, it will quit itself. The code to do that is here:

https://github.com/bazelbuild/bazel-watcher/blob/e8cbba37f5aa56f36e8561ec64128008c1f2cbe1/ibazel/ibazel.go#L95

I'm interested in feedback on how to improve it. What do you think?

**Comment by jmhodges** [comment] 2017-10-17 05:21
When I hit ctrl-c, I expect ibazel and the child process to be exited.

**Comment by achew22** [comment] 2017-10-17 05:26
My mental model is that it acts like a stack. When the parent process is started it starts a subprocess and that subprocess is absorbing everything you send to it. When you ctrl-c it kills the subtask and pops off the stack. 

To future implementors:

https://github.com/bazelbuild/bazel-watcher/blob/e8cbba37f5aa56f36e8561ec64128008c1f2cbe1/ibazel/ibazel.go#L96-L101

will need to be updated to attempt to kill the subprocess and die if it is successful. If it isn't then don't quit and increment the "no seriously, just die" counter.

**Comment by jmhodges** [comment] 2017-10-17 07:53
Ah, well, that UX doesn't line up with other tools I'm familiar with and made me think that ibazel was hung. I didn't expect it to kick up another command. I'm not so sure other folks won't think the same

**Comment by achew22** [comment] 2017-12-17 08:58
@jmhodges, I ended up using this functionality tonight to cancel my slow tests while they were running to fix issues without having to wait. The way I use this it seems like a feature not a bug (I hate that phrase) but I wanted to talk to you before closing this. Given the impedance mismatch have you been able to adjust to it working this way? What do you think now that this has been the behavior for a few months?

**Comment by achew22** [comment] 2018-12-02 21:31
Since this was filed we've improved the experience here by notifying users they need to trigger `SIGINT` again to quit.

https://github.com/bazelbuild/bazel-watcher/blob/master/ibazel/ibazel.go#L129

Marking as resolved.

**Closed by achew22** 2018-12-02 21:31 UTC
