### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bduffany** [bazelbuild/bazel-watcher#416] opened 2020-09-09 14:45 UTC
**Describe the bug**
I keep getting the following error:

```
iBazel [10:37AM]: Error getting Bazel info exit status 2
iBazel [10:37AM]: Querying for files to watch...
iBazel [10:37AM]: Error getting Bazel info exit status 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7a2a00]

goroutine 1 [running]:
main.(*IBazel).realLocalRepositoryPaths(0xc000150000, 0x921e00, 0xc0000a8120, 0x0)
        ibazel/ibazel_unix.go:31 +0x50
main.(*IBazel).queryForSourceFiles(0xc000150000, 0xc00030a020, 0x1d, 0x43d01f, 0xc00003d800, 0x4d7c1c, 0xc00030c014, 0x7ffe232b1091)
        ibazel/ibazel.go:454 +0x6e
main.(*IBazel).watchFiles(0xc000150000, 0xc00030a020, 0x1d, 0x91f800, 0xc00000e030)
        ibazel/ibazel.go:502 +0x5d
```

I saw an issue recently (#386) where this was supposedly fixed, but I think I am on the latest version of `ibazel` and I'm still seeing this problem. Also I think the issue is different - the earlier issue mentioned a broken WORKSPACE file, whereas the WORKSPACE file I'm working with is fine.

**Reproduction instructions**

I haven't yet found a consistent repro but I likely will in the next few days. The Git repo I'm working in is https://github.com/buildbuddy-io/buildbuddy (the issue happens when running `ibazel run server`). If I run `rm -rf node_modules` then the problem goes away temporarily. Not sure yet what causes it to pop back up.

Sometimes I'm using `USE_BAZEL_VERSION=3.4.0` so maybe that is messing with things. If I can isolate it to a particular pattern then I'll follow up.

**Version (please complete the following information):**
 - OS: Ubuntu 20.04
 - ibazel 0.13.1
 - Bazel 3.1.0

```
Bazelisk version: v1.6.1
Build label: 3.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Apr 22 10:32:27 2020 (1587551547)
Build timestamp: 1587551547
Build timestamp as int: 1587551547
```

**Comment by achew22** [comment] 2020-09-09 23:47
Hey Brandon, please say "hi" to Siggi and Tyler for me. Thanks for the bug report! I would love to look into this more once we get something reproducible. NPEs are the absolute worst and very maddening for both developers and consumers. `node_modules` is a tricky beast so I'm not super surprised that there is something going on in there. Any chance your `ibazel` is coming from `node_modules` instead of from the one on your system? ibazel, as it is distributed by npm, is actually a node script that tries to find a viable ibazel on your path. Could that be part of the issue?

**Comment by bduffany** [comment] 2020-09-10 13:42
Will do!

When I run `which ibazel` I get `~/.yarn/bin/ibazel` which is a symlink to `~/.config/yarn/global/node_modules/.bin/ibazel`, so I guess this means it's the one I installed with `yarn global add`? Let me know if there's anything else I can do to help

**Comment by bduffany** [comment] 2020-09-10 13:44
I did notice a pattern where I can only run `ibazel` without this exception if I first run `rm -rf node_modules`. So basically I have to run every `ibazel` command with `rm -rf node_modules && ibazel ...` otherwise I get the exception

**Comment by achew22** [comment] 2020-09-10 18:20
Could I have you build and run from master. It looks like I forgot to do a released since then. Lemme kick that off.

**Comment by achew22** [comment] 2020-09-10 20:03
I ran the "release this" program but it was stuck waiting for me to type in an OTP. I just found that tab in the background and now it is actually released. Sorry for the delay! I'm going to leave this open in case you run into it again, please comment on the bug. There is a bug autocloser that will close this after 60 days of inactivity or something like that, so NBD if you forget about it.

**Comment by jwnewman12** [comment] 2020-10-29 17:51
I can confirm this happens, when using the npm package @bazel/ibazel to run the program. If the node_modules/ dir is present, it segfaults. rm -rf, restart, works fine, until restart again with node_modules/ back.

Removing @bazel/ibazel from my machine, just building ibazel tool out of git, and moving it into $PATH works-for-me.

**Comment by achew22** [comment] 2020-10-29 18:55
I did a release this morning. Is this error report for v0.14?

**Closed** 2021-01-05 01:13 UTC
Labels: no-issue-activity
